spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/reservation
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update

  jwt:
    secret: ${SPRING_JWT_SECRET}
sms:
  accessKey: ${sms_accessKey}
  secretKey: ${sms_secretKey}
  serviceId: ${sms_serviceId}
  senderPhone: ${sms_senderPhone}
#token:
#  header: ${TOKEN_HEADER}
#  prefix: ${TOKEN_PREFIX}
