spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update

  redis:
    port: 6379
    host: localhost
    timeout: 30 #캐시 30분

  jwt:
    secret: ${SPRING_JWT_SECRET}
    time: 3600000
    header: "Authorization"
    prefix: "Bearer "

sms_accessKey: ${sms_accessKey}
sms_senderPhone: ${sms_senderPhone}
sms_serviceId: ${sms_serviceId}
sms_secretKey: ${sms_secretKey}
